### ISSUE TITLE
How to determine if host is VSTS or TFS (on premise)

### ISSUE THREAD

**Issue by mpseidel** [Microsoft/vss-web-extension-sdk#10]
Is there a supported way for an extension to determine if it is running inside VSTS or TFS on premise? Would love to have this info for usage tracking.

**Comment by miiitch** [comment]
You can do that:
`import Context = require("VSS/Context"); 
Context.getPageContext().webAccessConfiguration.isHosted
`

**Comment by mpseidel** [comment]
@miiitch thanks!! did I overlook this in the documentation?

**Comment by mpseidel** [comment]
@miiitch so just to be clear: `webAccessConfiguration.isHosted` would only be `true` in VSTS and `false` in TFS on prem?

**Comment by miiitch** [comment]
yes :)

**Comment by mpseidel** [comment]
Thanks. Closing the issue.
