### ISSUE TITLE
Not able to integrate third-party libraries when using TypeScript and AMD

### ISSUE THREAD

**Issue by janriemer** [Microsoft/vss-web-extension-sdk#113]
Hi,
we are having trouble to integrate third-party libraries (e.g. lodash) into our VSTS extension using TypeScript.

The loading of VSS components like `VSS/Controls` works fine, but third party libraries like [lodash](https://github.com/lodash/lodash) or [rxjs](https://github.com/ReactiveX/RxJS) fail to load with the following error:
`Error: Script error for: lodash
http://requirejs.org/docs/errors.html#scripterror basejs:53:860
c
http://<our-tfs-url>/_static/tfs/Dev14.M114/_scripts/TFS/min/basejs:53:860
onScriptError
http://<our-tfs-url>/_static/tfs/Dev14.M114/_scripts/TFS/min/basejs:53:11964
`

You can find a simple hello world extension that tries to make use of lodash in [this repository](https://github.com/janriemer/vsts-extension-hello-world).

We guess, the problem occurs due to AMD loader not being configured properly.
Ideally, we would like to use simple `import _ from 'lodash'` statements without having to repeat it in some configuration. Is there a way to do this?

Any help would be really appreciated.
Thank you.

**Comment by pabrams** [comment]
Yeah I've scratched my head over this too.  I'd assumed I was just stupid.

**Comment by MrTarantula** [comment]
I've submitted a PR to your "Hello World" extension for `packagePath` and no `packagePath` to show the changes needed.

**Comment by janriemer** [comment]
Hey @MrTarantula,
thank you very much for the elaborate answer and the PR! I haven't worked with AMD loaders yet. Things are much clearer now! :+1:
