### ISSUE TITLE
Code Coverage API calls are being blocked by CORS policy.

### ISSUE THREAD

**Issue by akhanna38** [Microsoft/vss-web-extension-sdk#126]
Code Coverage API calls are being blocked CORS policy.

```
import TFS_Test_Client = require("TFS/TestManagement/RestClient");
import { CodeCoverageSummary } from "TFS/TestManagement/Contracts";
const context = VSS.getWebContext();
const codeCoverageSummary : CodeCoverageSummary = await TFS_Test_Client
            .getClient()
            .getCodeCoverageSummary(
                context.project.id,
                build.id);
```

Expected Result:
it should get  Code Coverage Summary response/object back.

Actual Result:
Error message in console

GET https://xxx.visualstudio.com/xxx/_apis/test/CodeCoverage?buildId=14 net::ERR_ABORTED 401
Access to XMLHttpRequest at 'https://xxx.visualstudio.com/xxx/_apis/test/CodeCoverage?buildId=14' from origin 'https://xxx.gallerycdn.vsassets.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by akhanna38** [comment]
not an issue. Error reported was not correct. Manifest scope was not defined correctly.

**Comment by rozele** [comment]
What was the change required to manifest scope?

**Comment by akhanna38** [comment]
“Test” should be added to the scope in the manifest file

Thanks
Abhinav

**Comment by johnhultgren** [comment]
"scopes": [
    "vso.test"
]
