### ISSUE TITLE
Grid not showing any data in IE11 and Edge

### ISSUE THREAD

**Issue by riezebosch** [microsoft/vss-web-extension-sdk#129]
Even your [example](https://github.com/Microsoft/vsts-extension-samples/blob/master/contributions-guide/contextForm.html) doesn't work when adding dummy data. The grid shows but the rows remain empty. Is the control used anywhere in the default UI or is there another grid available?

**Comment by riezebosch** [comment]
In the meantime, I swapped out the grid and replaced it with react and Office UI. Only using the SDK for querying extension data.

**Comment by davidcorrigan714** [comment]
I think this is actually fixed now. It eventually broke in Chrome and when they fixed that it seems to have fixed it for IE as well.
