### ISSUE TITLE
Allow more contribution types like ms.vss-build-web.build-results-section to be invisible

### ISSUE THREAD

**Issue by mpseidel** [Microsoft/vss-web-extension-sdk#13]
The contribution type `ms.vss-web.tab` allows to show or hide a tab at runtime. Contributions of type `ms.vss-build-web.build-results-section` are always visible.

I would love to show or hide my `ms.vss-build-web.build-results-section` contribution ui depending on build propierties.

**Comment by willsmythe** [comment]
@mpseidel - this feature is available now. Look for `setSectionVisibility` in https://github.com/Microsoft/vsts-extension-samples/blob/master/build-results-enhancer/src/enhancer/status.ts

**Comment by mpseidel** [comment]
@willsmythe thanks for the update. great news :)

**Comment by LalinduPeiris** [comment]
Hi @willsmythe - I have check VSS SDK releases ,according to it latest release is M117. And according to comment in source you provided ,these changes available in M121. So this is yet to available?
 https://github.com/Microsoft/vss-web-extension-sdk/releases
