### ISSUE TITLE
Failed to load resource : the server responded with a status of 404()

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/vss-web-extension-sdk#33]
Using node_modules and AMD...  

My configuration widget can't find VSS.SDK

<img width="572" alt="failedtoload" src="https://cloud.githubusercontent.com/assets/10676026/23576260/44fcdfc6-0066-11e7-8898-eab8212f4bea.PNG">

The root cause of this is that the script source cannot be found and a get request is issued back to the server to retrieve it, it responds that it cannot find it. 

Here's is the content of configuration.html
<img width="398" alt="content" src="https://cloud.githubusercontent.com/assets/10676026/23576264/7190f518-0066-11e7-8af1-c95e3cb7245a.PNG">

But the HelloWorld widget can find VSS.SDK, as it loads no problem 

<img width="401" alt="hello" src="https://cloud.githubusercontent.com/assets/10676026/23576287/e7b892e6-0066-11e7-97e2-388aa04005ad.PNG">

When comparing the file sources in Chrome:

<img width="532" alt="loader" src="https://cloud.githubusercontent.com/assets/10676026/23576354/aa1407d4-0068-11e7-86c4-6ce79d5de13d.png">

The Project structure is:

<img width="113" alt="project" src="https://cloud.githubusercontent.com/assets/10676026/23576377/5415970c-0069-11e7-8757-bd0a779174e2.png">

And the vss-extension.json

```xml
{
  "manifestVersion": 1,
  "id": "HelloWorld",
  "version": "2.0.39",
  "name": "HelloWorld",
  "description": "A sample Visual Studio Services extension.",
  "publisher": "myName",
  "targets": [
    {
      "id": "Microsoft.VisualStudio.Services"
    }
  ],
  "icons": {
    "default": "images/logo.png"
  },
  "contributions": [
    {
      "id": "HelloWorld",
      "type": "ms.vss-dashboards-web.widget",
      "targets": [
        "ms.vss-dashboards-web.widget-catalog",
        ".HelloWorld.Configuration"
      ],
      "properties": {
        "name": "Hello World Widget 3 (with config)",
        "description": "My third widget which supports configuration.",
        "catalogIconUrl": "images/logo.png",
        "previewImageUrl": "images/logo.png",
        "uri": "HelloWorld.html",
        "supportedSizes": [
          {
            "rowSpan": 1,
            "columnSpan": 2
          }
        ],
        "supportedScopes": [
          "project_team"
        ]
      }
    },
    {
      "id": "HelloWorld.Configuration",
      "type": "ms.vss-dashboards-web.widget-configuration",
      "targets": [
        "ms.vss-dashboards-web.widget-configuration"
      ],
      "properties": {
        "name": "HelloWorldWidget Configuration",
        "description": "Configures HelloWorldWidget",        
        "uri": "templates/configuration.html"
      }
    }
  ],
  "scopes": [
    "vso.work"
  ],
  "files": [
    {
      "path": "HelloWorld.html",
      "addressable": true
    }, 
    {
      "path": "scripts",
      "addressable": true
    },
    {
      "path": "templates/configuration.html",
      "addressable": " true"
    },
    {
      "path": "node_modules/vss-web-extension-sdk/lib/VSS.SDK.js",
      "addressable": true
    }
  ]
}
```

I've tried altering the script src location many different times each without success.  In the samples, all of the references are to bower and they are not using AMD to load.  Perhaps this is root cause.

**Comment by shieldsjared** [comment]
@acousticguitar - your manifest is including 'VSS.SDK.js' but your HTML file is referencing 'VSS.SDK.min.js'.  They need to match.  You may also need to prepend your references with '../' to make it relative to the HTML file... but I'm not sure on that one without playing around with it.  Everything else looks good at a quick glance.

**Comment by AcousticGuitar** [comment]
doh!  Thanks for information Jared.
