### ISSUE TITLE
Is there a call to reload the entire extension?

### ISSUE THREAD

**Issue by broahmed** [Microsoft/vss-web-extension-sdk#37]
Hello there!

I've been searching the docs, so apologies if I've missed it.

I'm looking for a way to completely reload an extension. Does such a function call exist?

**Comment by cschleiden** [comment]
What type of extension?

**Comment by broahmed** [comment]
E.g. a custom tab/page extending the work item form.

I emailed vsointegration@microsoft.com and apparently there isn't a way to do this, so I'll be closing this. If you know differently, please feel free to comment!
