### ISSUE TITLE
Alternative to ms.vss-work-web.work-item-toolbar-menu

### ISSUE THREAD

**Issue by MrTarantula** [Microsoft/vss-web-extension-sdk#38]
With the new work item form, the toolbar menu is gone, but there is still the ... menu in the upper right corner. The [extension points page](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/targets/overview) only shows `ms.vss-work-web.work-item-toolbar-menu`. Is there currently an extension point that works in TFS 2017.1?

**Comment by cschleiden** [comment]
The work item context menu extension point also shows up there

**Comment by MrTarantula** [comment]
I've seen several projects that extend `ms.vss-work-web.work-item-context-menu` but that is no longer listed on the extension points page. In its place are `ms.vss-work-web.query-result-work-item-menu` and `ms.vss-work-web.backlog-item-menu`. None of those are adding the menu item in the new form, only the context menu.

From my vss-extension.json (I've tried all three targets):

```
"contributions": [{
      "id": "my-id",
      "type": "ms.vss-web.action",
      "description": "my-description",
      "targets": [
        "ms.vss-work-web.work-item-context-menu"
      ],
      "properties": {
        "uri": "index.html"
      }
    }
...
```

and from app.ts:

```
const myAction = {
    getMenuItems: (context: any) => {
        return [{
            action: (actionContext: IActionContext) => {
                //doing some work here
            },
            group: "actions",
            icon: "img/icon.png",
            text: "Text",
            title: "Title",
        } as IContributedMenuItem];
    },
};

VSS.register(`${extensionContext.publisherId}.${extensionContext.extensionId}.my-id`, myAction);
```

**Comment by cschleiden** [comment]
@MrTarantula Oh, good point. That is a documentation bug then. It works, see one of my example extensions here: https://github.com/cschleiden/vsts-quick-decompose/blob/master/vss-extension.json#L53

**Comment by MrTarantula** [comment]
I'm not sure what I'm doing wrong. The context menu works perfectly, but not the work item form menu. The code is never fired when the menu is clicked. Here's my extension, if you wouldn't mind taking a look:

https://github.com/MrTarantula/WIPrint

**Comment by MrTarantula** [comment]
I found the bug. I wasn't checking for null [here](https://github.com/MrTarantula/WIPrint/blob/master/scripts/app.ts#L43). It was failing silently, no errors in the console.

It's working now. I will close the issue.

**Comment by FlexiGit** [comment]
I have an extension on vsts targeting `ms.vss-work-web.work-item-context-menu`.
Since a few days the action is not listed in any of the context menus anymore. Has it silently been removed?

**Comment by MrTarantula** [comment]
I can't speak to the extension point on VSTS as I am using TFS, but if you have made any changes to your extension between then and now, you should go back and thoroughly check for bugs. The console showed nothing at all when my failure was happening. Very annoying, but in my experience null references crop up often, even with TypeScript.

**Comment by FlexiGit** [comment]
The main problem is: I haven't made any changes. The last version was published on April 17th. And it was working as expected afterwards. And I am sure all was working fine last week (at least till Wednesday). I am also sure that the extension does load correctly, because it has another contribution (settings page on admin hub) which is working.

**Comment by MrTarantula** [comment]
My other contributions loaded too. That doesn't necessarily mean there isn't a failure somewhere. I just tested my [Work Item Print](https://marketplace.visualstudio.com/items?itemName=mrtarantula.wiprint) extension in VSTS and it is 100% functional. Give it a shot. You can see it has a couple of contributions, [one targeting `ms.vss-work-web.work-item-context-menu`](https://github.com/MrTarantula/WIPrint/blob/master/vss-extension.json#L65).

I would still go back and check for bugs, but if this is a legitimate problem then you should create your own issue for better visibility. My issue is closed.

**Comment by FlexiGit** [comment]
Was your context menu action (the containing iframe) showing up in the browser debugger when you had the error?

**Comment by MrTarantula** [comment]
Yes, all my files loaded fine. I had to set breakpoints line by line to trap the failure. Look at my last commit. I didn't check that context.workItemIds existed and it broke the contribution, but left the other one alone.

**Comment by FlexiGit** [comment]
Ok, there is my next problem: I don't see my action iframe in F12 tools :(

**Comment by MrTarantula** [comment]
If I don't have dev tools open already, then I have to refresh for the files to show up. If that doesn't work then you do have a problem, either with your vss-extension.json or the VSS bootstrapping.

**Comment by FlexiGit** [comment]
Ok, I found the problem. It was not the target of the contribution. It was the type.
This was my first extension adapting the new mechanism. And from the examples back then I copied the type `ms.vss-web.action-provider`. 
In AppInsights I can see, that this was working fine till May 24th. And after that it didn't, no error, no warning, nothing.
Changing the type to `ms.vss-web.action` fixed it.

**Comment by MrTarantula** [comment]
I've also been confused by `action-provider` and `action`. Older examples seem to use `action-provider`, and newer ones `action`, but I have seen no documentation for the change. I can use either on TFS 2017 and notice no difference. 

It would be great if there were a changelog that would show deprecated methods, properties, and values.

**Comment by mmanela** [comment]
ms.vss-work-web.work-item-toolbar-menu should work on the new work item form to put your item in the menu. Is that not working for you @MrTarantula  and @FlexiGit ?

**Comment by MrTarantula** [comment]
`ms.vss-work-web.work-item-context-menu` works for both the context menu and the menu within the work item. `ms.vss-work-web.work-item-toolbar-menu` only works in TFS 2015.

Related: will there be extension points to hook into the new Work Items hub?
