### ISSUE TITLE
Trying to perform an action after work item form is closed

### ISSUE THREAD

**Issue by MrTarantula** [Microsoft/vss-web-extension-sdk#39]
In a custom hub, I am opening work items. What I want to do is wait for the work item to be closed (saved or not doesn't matter) and then perform an action. Here is an example:
```
import WITService = require("TFS/WorkItemTracking/Services");
const witService = WITService.WorkItemFormNavigationService.getService();

witService.then(service => service.openWorkItem(id));
```

Chaining `.then()` on `service.openWorkItem(id)` or anywhere else performs the action as soon as the work item form promise is fulfilled. What I want is something like the `onUnload` listener, but I would like to contain it to this hub. Does this functionality exist?

**Comment by MrTarantula** [comment]
I have added an `onUnloaded` observer, and it is working, but it is not having the desired effect. I want to call an function on my hub during `onUnloaded` but I think the call never makes it back to the hub. Is there something like a hub observer that the work item form can talk to?

I tried registering an object with `VSS.register()` but either I'm not doing it right or it's not intended for what I am trying to do.

**Comment by mohitbagra** [comment]
@MrTarantula  The "openWorkItem" function now returns a promise which resolves after the dialog is closed and the resolved promise returns a work item object that has most recent field values for the workitem at the time it was closed. You can get more info on this [here](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/api/tfs/workitemtracking/services/workitemformnavigationservice)
