### ISSUE TITLE
Define is not Defined

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/vss-web-extension-sdk#41]
**Problem :** Attempting to create simple hello world vsts extension.  When it loads, I am seeing  Define is not defined at load time.  The js file will not fully load because of this error. 

**Internals**

In my HTML I'm trying to load the dist/app.js file.

![image](https://cloud.githubusercontent.com/assets/10676026/26159489/52585eda-3ae4-11e7-949f-32d60be1938d.png)

My TSConfig.json looks like this:
![image](https://cloud.githubusercontent.com/assets/10676026/26159915/749a4c8c-3ae5-11e7-9062-c1d120f52701.png)

The file dist/app.js is found and the load is attempted, but Chrome shows me this error.

![image](https://cloud.githubusercontent.com/assets/10676026/26159856/50ea63bc-3ae5-11e7-8031-1da3436df554.png)

I've scoured the internet and cannot find a solution..
I tried npm install requirejs
I tried npm install amd-loader and put in this line (in app.ts) require("amd-loader");
I cannot change the module system to umd or commonjs because the extension SDK requires AMD

**Comment by cschleiden** [comment]
You have to load `app.js` via our module loader (or your own requirejs setup). See this example https://github.com/cschleiden/vsts-extension-ts-seed-simple/blob/master/index.html

**Comment by pabrams** [comment]
Please improve the error message.  "Define is not Defined" is terrible.
