### ISSUE TITLE
VSS generated error messages could be improved

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/vss-web-extension-sdk#42]
Consider the following code snippet...

```
<script type="text/javascript">
        VSS.init({
            explicitNotifyLoaded: true,
            usePlatformStyles: true,
            configureModuleLoader:true
        });

        VSS.require("TFS/Dashboards/WidgetHelpers", function (WidgetHelpers) {
            WidgetHelpers.IncludeWidgetStyles();
            VSS.register("ToolWidget", function () {
                return {
                    load: function (widgetSettings) {
                        var $title = $('h2.title');
                        $title.text('Hello World');

                        return WidgetHelpers.WidgetStatusHelper.Success();
                    }
                }
            });
            VSS.notifyLoadSucceeded();
        });
    </script>
```
This is a very typical boot up sequence for creating a VSTS Extension.  Three main areas within VSS Support are VSS.Init, VSS.Require and VSS.Register.  VSS.notifyLoadSucceded never fails but the others do fail.  When VSS issues errors, the messages are cryptic and require super-human effort to find the root cause. 

For example: 

`VSS.SDK.js:652 No handler found on any channel for message: {"id":1,"methodName":null,"instanceId":"ToolWidget","params":null,"jsonrpc":"2.0"}`

This message says nothing to the end user regarding the root of the problem.  The root cause being that the ID passed into VSS.Register was not found in the vss.extension.json contribution section.  

the main choke points are VSS.Init, VSS.Require and VSS.Register all of them have to work together to run properly but if any one of the parms, is out of whack, it's good luck finding it time...

**Comment by martinfletcher** [comment]
I am having a similar error:

VSS.SDK.js:652 No handler found on any channel for message: {"id":1,"methodName":null,"instanceId":"[PUBLISHER].[EXTENSION_ID].[CONTRIBUTION]"}

With the following setup:

"contributions": [
    {
      "id": "[HUB_ID]",
      "type": "ms.vss-web.hub",
      "description": "",
      "targets": [
        "ms.vss-work-web.work-hub-group"
      ],
      "properties": {
        "name": "HUB",
        "uri": "static/hub/index.html"
      }
    },
    {
      "id": "HUB_EXTENSION",
      "type": "ms.vss-work-web.work-item-notifications",
      "description": "",
      "targets": [
        "ms.vss-work-web.work-item-form"
      ],
      "properties": {
        "uri": "static/hub/event-handlers.html"
      }
    }
  ],

VSS.init({
    usePlatformScripts: true
});

VSS.ready(() => {

    VSS.require(["VSS/Service", "TFS/WorkItemTracking/RestClient"], function (VSS_Service, TFS_Wit_WebApi) {

        let client = TFS_Wit_WebApi.getClient();
        let log = (msg, data) => {

            console.log(`${msg}: ${JSON.stringify(data)}`);

        };

        VSS.register(/* VSS.getContribution().id - Does noit work either */ 'Kukd.WorkItems.Estimates.Rollup', (ctx) => {

            return {
                onSaved: (args) => {
                              ......
                    }
            };

        });

        VSS.notifyLoadSucceeded();

    });    

});

Any help would be great, as there is very little documentation about this error.

**Comment by mpseidel** [comment]
@willsmythe getting this error as well in the Personas extension. The extension works fine but I'd rather get rid of that nasty error.

**Comment by mpseidel** [comment]
@martinfletcher do you still see the error in your project?

**Comment by martinfletcher** [comment]
I am indeed still getting the error...

**Comment by mpseidel** [comment]
@martinfletcher have you set `explicitNotifyLoaded` to true?
With this setup the error does not show for me:

```
        VSS.init({
            explicitNotifyLoaded: true,
            usePlatformScripts: true
        });

        VSS.ready(function () {
            VSS.register(VSS.getContribution().id, function (context) {
                return {
                    // ...
                  };
            });

            VSS.notifyLoadSucceeded();
        });
```

**Comment by martinfletcher** [comment]
Apologies for the late reply, yes that was indeed the issue. Needed to set explicitNotifyLoaded: true, and call notifyLoadSucceeded()

**Comment by mpseidel** [comment]
@martinfletcher glad this fixed it for you!

**Comment by newtonsheikh** [comment]
This is probably the dirtiest error i got and only please found some help was this issue disucssion :) 

The below code worked for me, hope it helps someone 

 `<script type="text/javascript">
        VSS.init({
            explicitNotifyLoaded: true,
            usePlatformScripts: true,
            usePlatformStyles: true
        });

        VSS.ready(function () {
            VSS.register("Modal-Form", function (context) {
                return {};
            });

            VSS.notifyLoadSucceeded();
        });
    </script>`

**Comment by rdileep** [comment]
Thanks Guys, This solved my problem too.

**Comment by shreshthijain** [comment]
Hi I have tried everything mention. but still I get the same error.
