### ISSUE TITLE
IContributedMenuItem Icon/CSSClass

### ISSUE THREAD

**Issue by MrTarantula** [microsoft/vss-web-extension-sdk#44]
Although the [docs](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/api/vss/references/vss_sdk_interfaces/icontributedmenuitem) say that an `IContributedMenuItem` icon can be a CSS class, the icon string is only ever added as a URL, unless I am missing something. 

If the functionality does not exist, I would like to have the `cssClass` property added to the menu-item-icon span for `IContributedMenuItem`. It should behave like the `cssClass` property of [`IMenuItemSpec`](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/controls/menubar). This will make it easier for devs to use the platform styles and "bowtie" icons in context menus.

**Comment by willsmythe** [comment]
@dwilsonmsft - can you take a look at this? I'm assuming @MrTarantula has worked through this, but getting the right guidance / updates docs in place would be good regardless.

**Comment by MrTarantula** [comment]
I'm using a png where I want to use an icon. This is only a problem when supporting 2015, 2017, and VSTS. The icon sizes are a little different in context menus and toolbars between versions, so I need to have a 14x14 and 16x16 image to use in the different contexts, or the images are too big/small and aren't consistent with the VSTS theme. Adding a class like `bowtie-icons` instead of an image matches the rest of the context menu.
