### ISSUE TITLE
Multiselect Grids

### ISSUE THREAD

**Issue by MrTarantula** [microsoft/vss-web-extension-sdk#46]
Grids have the option of being multiselect. How do I access all selected items? The [documentation](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/controls/grid) is not very helpful. Also, how can I perform an action when one or more items are selected? Not double-clicked, just selected or multi-selected.

**Comment by MrTarantula** [comment]
getSelectedDataIndices() or getSelectedRowIndices() will get the data, but I can't figure out how to fire an event on selecting. onRowClick() seems like an obvious one but I can't find any documentation on it and it doesn't fire when a row is clicked.

**Comment by cschleiden** [comment]
@serkan-inci ?
