### ISSUE TITLE
Access modifier error

### ISSUE THREAD

**Issue by MrTarantula** [Microsoft/vss-web-extension-sdk#48]
I just cloned an extension that had been working, and now when I try to package it I receive the following error:

```
typings/globals/vss/index.d.ts(20666,14): error TS2415: Class 'Component<TProps, TState>' incorrectly extends base class 'React.Component<TProps, TState>'.
  Property 'componentDidMount' is protected in type 'Component<TProps, TState>' but public in type 'Component<TProps, TState>'.
typings/globals/vss/index.d.ts(20700,14): error TS2415: Class 'Component<TControl, TProps, TState>' incorrectly extends base class 'Component<TProps, TState>'.
  Property 'shouldComponentUpdate' is protected in type 'Component<TControl, TProps, TState>' but public in type 'Component<TProps, TState>'.
```

**Comment by MrTarantula** [comment]
Changing the access modifiers in `typings/globals/vss/index.d.ts` fixes the compilation problem. I don't know whether this was a change in React or VSS SDK, and I don't want to go through the commit history of a 33,000 line file to investigate.

**Comment by GScully** [comment]
New to TS can you elaborate on the fix?

**Comment by MrTarantula** [comment]
The root cause is because of differing versions of TS installed globally vs what's in the SDK, as mentioned in #50. I'm now using the [ALM Rangers yeoman generator](https://github.com/ALM-Rangers/generator-vsts-extension) for my extensions and haven't run into any issues yet. You can always just downgrade your TS version. 

I'm going to close this issue.

**Comment by GScully** [comment]
Thanks I'll give this package a try. I appreciate the response.
