### ISSUE TITLE
Registering Objects in TFS2015 and 2017

### ISSUE THREAD

**Issue by MrTarantula** [microsoft/vss-web-extension-sdk#49]
I've been informed that a simple context menu item extension I've created does not work in TFS 2015, but does in 2017 and VSTS. I was able to trace it to 
```
const extensionContext = VSS.getExtensionContext();

//some code

VSS.register(`${extensionContext.publisherId}.${extensionContext.extensionId}.my-contribution`, contribFunction);
```

In TFS 2015, I receive the error `No handler found on any channel for message` and the menu item does not appear. On 2017/VSTS it's fine. If I remove `${extensionContext.publisherId}.${extensionContext.extensionId}.` and just keep the id simple it works in 2015 with no error, but on VSTS I receive the `No handler found on any channel for message` error but the context menu item still appears and works.

Is this expected behavior? Am I supposed to dynamically change the registered object id based on TFS version?

**Comment by MrTarantula** [comment]
In the error message TFS 2015 is expecting the short id, and 2017/VSTS is expecting `publisherid.extensionid.my-contribution`.

**Comment by MrTarantula** [comment]
I can't find an API for telling me the version of TFS, so I just register everything twice:

```ts
VSS.register(`${extensionContext.publisherId}.${extensionContext.extensionId}.my-contribution`, contribFunction);
VSS.register(`my-contribution`, contribFunction);
```

No conflicts or errors yet, and it keeps me from maintaining two separate extensions. Hope this helps someone with the same problem.

**Comment by willsmythe** [comment]
@dmarcey - can you validate this is the best option for developers that need to support TFS and VSTS (including older versions of TFS)?

**Comment by MrTarantula** [comment]
Somewhat related, I am trying to find a way to query conversation history that is compatible with both TFS 2015 and VSTS. In the latest SDK, `WITClient.getHistoryById()` is gone, and replaced with `WITClient.getComments()`. Is it possible to use multiple versions of the SDK, or do I have to create and maintain separate contribution for the different TFS versions?

Is there a list somewhere of deprecated functions, so extension devs can keep their extensions working and future-proof?

**Comment by MrTarantula** [comment]
Also related, this is the best way I could find to differentiate TFS 2015 and 2017/VSTS:

```ts
const vssContext = VSS.getWebContext();
if (vssContext.account.name === "TEAM FOUNDATION") {
     //do stuff
}
```

2015 is `TEAM FOUNDATION`, 2017 is `Team Foundation Server`, and VSTS is the actual account name. Maybe this will be helpful to somebody.
