### ISSUE TITLE
Charts/Services with Typescript

### ISSUE THREAD

**Issue by acsatis** [Microsoft/vss-web-extension-sdk#58]
Hello,

I'm trying to create an extension with this sdk, but I don't see any typescript definition file from Charts/Services. How can I use this API from TypeScript? I need to write my own d.ts ?

Thanks the help!

**Comment by PeterAntal** [comment]
Sorry on the inconvenience.

Charting types and typescript contracts did not get added with the extension SDK payload when it was initially documented and made public. That omission in d.ts was recently updated for inclusion, it will be rolling out with the next publish cycle on the extension sdk, which should happen in next few days.

Until that update reaches you, you will need to temporarily use your own temporary types or any casts.

The types are definitely a key part of the Chart SDK/Docs for discovery of the contract capabilities and allowed values, for which we'd be happy to hear feedback, once you start using it.

Kind Regards!

**Comment by serkan-inci** [comment]
Chart types are added with M125 version.
