### ISSUE TITLE
VSTS work item callbacks

### ISSUE THREAD

**Issue by biggless** [Microsoft/vss-web-extension-sdk#61]
From documentation I found this callbacks:

- onFieldChanged
- onLoaded
- onUnloaded
- onSaved
- onReset
- onRefreshed

I'm interested in onSaved and it works fine if I use save button. But when I click "Save & close" this callback does not work at all. Is there any way to handle save&close event?

**Comment by cschleiden** [comment]
That should work, let me check.

**Comment by mohitbagra** [comment]
These event handlers have a limitation in work item dialog scenario. When the dialog is closed, we dispose all the elements inside it, including form extensions. And we close the dialog as soon as Save finishes. We are looking for a good solution for this scenario but right now we dont have one.

**Comment by MrTarantula** [comment]
Does the solution from #39 work for your issue? It's not a callback, but a `Promise<WorkItem>` that's returned after the form is closed.

**Comment by biggless** [comment]
Will check this, thanks!
