### ISSUE TITLE
Missing hub for "Build and Release" tab 

### ISSUE THREAD

**Issue by vbossica** [Microsoft/vss-web-extension-sdk#62]
Writing a new hub contribution, it is possible to attach it to the `ms.vss-work-web.work-hub-group` or `ms.vss-code-web.code-hub-group` but I can't find the hub name for the new "Build and Release" tab.

The [documentation](https://docs.microsoft.com/en-us/vsts/extend/reference/targets/overview#hubs-and-hub-groups) seems outdated as it mentions the now removed individual _Build_ and _Release_ hubs.

**Comment by cschleiden** [comment]
It's `ms.vss-build-web.build-release-hub-group`.

@willsmythe can you update the documentation?

**Comment by mongeon** [comment]
It have been added, this issue could be closed :)
