### ISSUE TITLE
npm run build results in: TS2304: Cannot find name Iterable

### ISSUE THREAD

**Issue by japj** [microsoft/vss-web-extension-sdk#63]
When I run npm run build, this results in:

node_modules/@types/jquery/index.d.ts(2961,63): error TS2304: Cannot find name 'Iterable'.

It seems that some tsconfig.json settings are missing?
I found that if I add lib options for es2015 and dom then it compiles ok, but I don't know enough typescript to determine if this is the "right" solution:

"compilerOptions": {
        **"lib" : ["es2015","dom"]**
}

**Comment by serkan-inci** [comment]
Hi japj, 

We are investigating this issue, Thanks

Serkan Inci

**Comment by kirakosyan** [comment]
Hi
probably will help to investigate, having same issue in project which has typescript when changed target in tsconfig from es6 to es5

any workaround for it ?
