### ISSUE TITLE
How to redraw a chart control after changing widget configuration 

### ISSUE THREAD

**Issue by jmelosegui** [microsoft/vss-web-extension-sdk#70]
I have created a custom widget for TFS 2017 on premises that uses a chart control to render some data.

```typescript
export class RankingWidget implements IConfigurableWidget {
    public load(widgetSettings: WidgetSettings) {
        return this.drawChart(widgetSettings);
    }

    public reload(widgetSettings: WidgetSettings) {
        return this.drawChart(widgetSettings);
   }
}
```

The `draw` method is in charge of creating the chart and assigning the data to render.
The problem is that the reload method is not redrawing the instance of the chart that was created during the load method. 

Also, there is no way to obtain the instance of the chart after using

```typescript
 chartService.createChart($container, $chartOptions);
```

since `createChart` return void.

can anyone advise how to redraw the chart after changing the data inside the `series: DataSeries`  of the `CommonChartOptions`

**Comment by arvindsingh-cloud** [comment]
Hi @jmelosegui jmelosegui did you find solution for this

**Comment by jmelosegui** [comment]
Nop, I have to close and reopen the settings dialog.
