### ISSUE TITLE
Changelog please?

### ISSUE THREAD

**Issue by MrTarantula** [microsoft/vss-web-extension-sdk#84]
A changelog would be nice to have, so that developers know what features/fields are gone from VSTS. We can't be expected to sift through diffs of several 6000+ line typings files to find what has changed. Right now I only know of API changes when users report that my extension is broken. It would also be helpful to mark things as deprecated/obsolete before removing them.

**Comment by nschonni** [comment]
Not to highjack the tread, but if you go back to tagging your releases like you used to (https://github.com/Microsoft/vss-web-extension-sdk/releases) it at least makes it possible to bisect the releases
