### ISSUE TITLE
401 when accessing releases in dashboard extension

### ISSUE THREAD

**Issue by ptrstpp950** [Microsoft/vss-web-extension-sdk#86]
I'm trying to write a custom dashboard extension, but following code gives me 401

> VSS.require(["TFS/Dashboards/WidgetHelpers", "TFS/Build/RestClient", "Charts/Services", "ReleaseManagement/Core/RestClient"],
>         function (WidgetHelpers, TFS_Build_WebApi, TFS_Charts, TFS_ReleaseManagment) {
>             WidgetHelpers.IncludeWidgetStyles();
>             var projectId = VSS.getWebContext().project.id;
> 
>             TFS_ReleaseManagment.getClient().getReleases("projectId").then(
>                         function(x){
>                             debugger;
>                             console.log(x);
>                         }
>                     );

I included release management in vss-extension.json as

>  "contributions": [
>         {
>             "id": "xxxx.build-overview-widget",
>             "type": "ms.vss-dashboards-web.widget",
>             "description": "A dashboard widget to many releases in one dashboard",
>             "includes": [ "ms.vss-releaseManagement-web.release-service-data-external" ],
>             "targets": [
>                 "ms.vss-dashboards-web.widget-catalog"
>             ],

**Comment by Bakanych** [comment]
I also can reproduce this. Any updates?

**Comment by ptrstpp950** [comment]
@Bakanych Forget about it. I don't remember what was my mistake, but it was my error
