### ISSUE TITLE
Unit testing guidance

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vss-web-extension-sdk#89]
I'm having a really hard time trying to add some unit testing to my web extension.

Is there any guidance on this anywhere?  Has anyone successfully done it?  I've tried various tutorials for Karma, Jasmine, Mocha/Chai, and nothing is working.  I usually end up hitting a wall with `define is not defined`, which leads me to internet advice that says to use `commonjs` instead of `amd` as my module, but when I do that I get other errors, like my VSS SDK imports can't be found.

**Comment by MrTarantula** [comment]
Install [`amd-loader`](https://github.com/ajaxorg/node-amd-loader) as a development dependency: `npm i amd-loader --save-dev` along with your testing framework, then include this at the top of each test file: `require('amd-loader');`.

**Comment by pabrams** [comment]
@MrTarantula  Thanks for the advice!  I tried this, but the tests still fail to compile - they can't find most of the dependencies of my test targets.  I forgot to mention I'm also using webpack.  Do I need to configure this in webpack somehow?
The dependencies it can't find are stuff like 
`import Utils_Date = require("VSS/Utils/Date");`
And I don't really understand how those are found anyway, since I don't have those folders.  There's weird stuff that I don't understand going on in webpack config and vss-extension.json.

In case it helps, here's my webpack config:

```
const path = require("path");
const webpack = require("webpack");

module.exports = env => {
    const plugins = [];
    if (env && env.substring(0, 4) === "prod") {
        plugins.push(
            new webpack.optimize.UglifyJsPlugin({
                compress: {
                    warnings: false,
                },
                output: {
                    comments: false,
                },
            })
        );
    }
    return {
        entry: {
            "main": "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Extension.ts")),
            "calendarServices": "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "CalendarServices.ts")),
            "freeformEventControl":  "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Controls", "FreeFormEventControl.ts")),
            "capacityEventControl":  "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Controls", "CapacityEventControl.ts"))
        },
        output: {
            filename: path.relative(process.cwd(), path.join(__dirname, "dist", "[name].js")),
            libraryTarget: "amd",
        },
        externals: [
            {
                react: true,
                "react-dom": true,
            },
            /^TFS\//, // Ignore TFS/* since they are coming from VSTS host
            /^VSS\//, // Ignore VSS/* since they are coming from VSTS host
        ],
        resolve: {
            alias: { OfficeFabric: "../node_modules/office-ui-fabric-react/lib-amd" },
            extensions: [".ts", ".tsx", ".js"],
        },
        module: {
            rules: [{ test: /\.tsx?$/, loader: "ts-loader" }],
        },
        plugins: plugins,
    };
};
```

**Comment by pabrams** [comment]
@MrTarantula  Thanks for the advice!  I tried this, but the tests still fail to compile - they can't find most of the dependencies of my test targets.  I forgot to mention I'm also using webpack.  Do I need to configure this in webpack somehow?
The dependencies it can't find are stuff like 
`import Utils_Date = require("VSS/Utils/Date");`

And I'm not surprised it can't find them, since there is no VSS folder.  Actually, I'm confused how that SDK is found at all (I forked this from [Microsoft/vsts-team-calendar](https://github.com/Microsoft/vsts-team-calendar) and inherited their setup, which I still don't understand).  I guess vss-extension.json maps "skd" to a subfolder in node_modules:
```
        {
            "path": "node_modules/vss-web-extension-sdk/lib",
            "addressable": true,
            "packagePath": "sdk"
        },
```
and one of the html files, which is an entry point for the hub item, loads the SDK as a script from that fake "sdk" folder:
```
<head>
    <script src="../sdk/VSS.SDK.min.js"></script>
```
and then it initializes the SDK:
```
        VSS.init({
            explicitNotifyLoaded: true,
            moduleLoaderConfig: {
                paths: {
                    "Calendar": "js"
                }
            }
        });
        VSS.require(["Calendar/calendarServices"], function (FreeFormEventsSource, VSOCapacityEventSource, VSOIterationEventSource) {
            VSS.notifyLoadSucceeded();
        });
```

And I guess the "js" location is found by another weird mapping thing in vss-extension.json:
```
        {
            "path": "dist",
            "packagePath": "js",
            "addressable": true
        },
```
And I actually *do* have a dist folder, where webpack drops some .js files.

In case it helps, here's my webpack config:

```
const path = require("path");
const webpack = require("webpack");

module.exports = env => {
    const plugins = [];
    if (env && env.substring(0, 4) === "prod") {
        plugins.push(
            new webpack.optimize.UglifyJsPlugin({
                compress: {
                    warnings: false,
                },
                output: {
                    comments: false,
                },
            })
        );
    }
    return {
        entry: {
            "main": "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Extension.ts")),
            "calendarServices": "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "CalendarServices.ts")),
            "freeformEventControl":  "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Controls", "FreeFormEventControl.ts")),
            "capacityEventControl":  "./" + path.relative(process.cwd(), path.join(__dirname, "src", "Calendar", "Controls", "CapacityEventControl.ts"))
        },
        output: {
            filename: path.relative(process.cwd(), path.join(__dirname, "dist", "[name].js")),
            libraryTarget: "amd",
        },
        externals: [
            {
                react: true,
                "react-dom": true,
            },
            /^TFS\//, // Ignore TFS/* since they are coming from VSTS host
            /^VSS\//, // Ignore VSS/* since they are coming from VSTS host
        ],
        resolve: {
            alias: { OfficeFabric: "../node_modules/office-ui-fabric-react/lib-amd" },
            extensions: [".ts", ".tsx", ".js"],
        },
        module: {
            rules: [{ test: /\.tsx?$/, loader: "ts-loader" }],
        },
        plugins: plugins,
    };
};
```

Also don't understand the purpose of this excerpt from vss-extension.json:

```
    "files": [
        {
            "path": "static/images",
            "addressable": true
        },
        {
            "path": "static/css",
            "addressable": true
        },
        {
            "path": "dist",
            "packagePath": "js",
            "addressable": true
        },
        {
            "path": "node_modules/vss-web-extension-sdk/lib",
            "addressable": true,
            "packagePath": "sdk"
        },
```

and my tsconfig in  case that matters

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "noUnusedLocals": true,
        "module": "amd",
        "moduleResolution": "node",
        "target": "es5",
        "outDir": "dist/",
        "rootDir": "src/",
        "lib": [
            "es5",
            "dom",
            "es2015.promise"
        ],
        "importHelpers": true,
        "noEmitHelpers": true,
        "skipLibCheck": true,
        "types": [
            "vss-web-extension-sdk",
            "fullcalendar",
            "jquery"
        ]
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

**Comment by MrTarantula** [comment]
I believe that all the SDK does is add some handlers to the extension iframe within VSTS to bootstrap the extension. The extension tells VSTS what it is and what it needs, and VSTS provides the scripts. 

There is no way to test these integrations without loading in VSTS/TFS. Maybe with something like PhantomJS, but you'll have to figure out the auth and such. Anyway, those would be integration tests, not unit tests.

For unit tests, you would need to decouple your code from the SDK as much as you can and test that.

**Comment by pabrams** [comment]
That makes sense.  Thanks for the help @MrTarantula
