### ISSUE TITLE
getTeamMembersWithExtendedProperties doesn't work

### ISSUE THREAD

**Issue by davesmits** [microsoft/vss-web-extension-sdk#94]
I just updated my project to the latest (134) version of the VSS web extension sdk. in my project I been using:

````
import * as CoreRestClient from "TFS/Core/RestClient";
const client = CoreRestClient.getClient();
client.getTeamMembers(projectId, teamId, undefined, undefined)
````

after I upgraded I was unable to compile my typescript because the method `getTeamMembers` was no longer existing. I changed my code to start using `getTeamMembersWithExtendedProperties` but after publishing to VSTS getting an error that this method didn't exist. 

Now to work around it I am first casting my client to any type and then call `getTeamMembers` again as I was doing before the upgrade

**Comment by sitwalkstand** [comment]
I am having the same issue.  Using latest version (134) and have to do the same casting trick to get team members to return.

**Comment by HusnuAkcak** [comment]
I am using version "5.141.0" and I had to use `getTeamMembersWithExtendedProperties ` method instead of `getTeamMembers`
